package de.tudarmstadt.rxrefactoring.core.ir;

import java.util.List;

import org.eclipse.jdt.annotation.NonNull;
import org.eclipse.jdt.core.dom.ParameterizedType;
import org.eclipse.jdt.core.dom.SimpleName;
import org.eclipse.jdt.core.dom.Type;

import de.tudarmstadt.rxrefactoring.core.IRewriteCompilationUnit;
import de.tudarmstadt.rxrefactoring.core.NodeSupplier;
import de.tudarmstadt.rxrefactoring.core.internal.execution.RewriteCompilationUnit;

public interface IReactiveComputation {

	/**
	 * Produces the type of the input.
	 */
	public @NonNull NodeSupplier<? extends Type> supplyType();
	
	/**
	 * Produces the type of the flowable that is generated by this computation.
	 */
	default @NonNull NodeSupplier<ParameterizedType> supplyFlowableType() {
		return NodeSupplier.parameterizedType(NodeSupplier.simpleType("Flowable"), supplyType());
	}
	
	/**
	 * Produces the internal name that is used to reference this computation.
	 */
	public @NonNull NodeSupplier<SimpleName> supplyInternalName();
	
	/**
	 * Adds this computation to a list of body declaration.
	 * 
	 * @param unit The unit that should contain the declaration.
	 * @param bodyDeclarations The list of declarations to which the
	 * computation is added.
	 */
	public void addToTypeDeclaration(@NonNull IRewriteCompilationUnit unit, @NonNull List<?> bodyDeclarations);
	
	
	
}
