/*
 * SettingsWindow.java
 *
 * Created on May 8, 2011, 7:38:10 PM
 */
package ru.ifmo.juneiform.ui;

import javax.swing.JFileChooser;
import ru.ifmo.juneiform.L10n;
import ru.ifmo.juneiform.Settings;
import ru.ifmo.juneiform.Utils;

/**
 *
 * @author Oleg "xplt" Kuznetsov
 */
public class SettingsWindow extends javax.swing.JDialog {
    
    private Settings settings;
    
    /** Creates new form SettingsWindow */
    public SettingsWindow() {
        initComponents();
    }
    
    public SettingsWindow(Settings settings) {
        this();
        this.settings = settings;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customCuneiformCheckBox = new javax.swing.JCheckBox();
        pathLabel = new javax.swing.JLabel();
        pathTextField = new javax.swing.JTextField();
        fileChooserButton = new javax.swing.JButton();
        defaultLanguageLabel = new javax.swing.JLabel();
        recognitionLanguageComboBox = new javax.swing.JComboBox();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(L10n.forString("settings.title")); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        customCuneiformCheckBox.setText(L10n.forString("settings.custom.cuneiform")); // NOI18N
        customCuneiformCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customCuneiformCheckBoxActionPerformed(evt);
            }
        });

        pathLabel.setText(L10n.forString("settings.path.label")); // NOI18N

        pathTextField.setText(L10n.forString("settings.path.default")); // NOI18N
        pathTextField.setToolTipText(L10n.forString("settings.path.tooltip")); // NOI18N
        pathTextField.setEnabled(false);

        fileChooserButton.setText(L10n.forString("settings.choose.button")); // NOI18N
        fileChooserButton.setEnabled(false);
        fileChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserButtonActionPerformed(evt);
            }
        });

        defaultLanguageLabel.setText(L10n.forString("settings.language.label")); // NOI18N

        recognitionLanguageComboBox.setModel(Utils.languageComboBoxModel());

        saveButton.setText(L10n.forString("settings.save.button")); // NOI18N
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(L10n.forString("settings.cancel.button")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customCuneiformCheckBox)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(defaultLanguageLabel)
                                .addGap(18, 18, 18)
                                .addComponent(recognitionLanguageComboBox, 0, 192, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(pathLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pathTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fileChooserButton)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addGap(142, 142, 142))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customCuneiformCheckBox)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pathLabel)
                    .addComponent(fileChooserButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(defaultLanguageLabel)
                    .addComponent(recognitionLanguageComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void customCuneiformCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customCuneiformCheckBoxActionPerformed
        if (pathTextField.isEnabled() || fileChooserButton.isEnabled()) {
            disableFields();
            setDefaultCuneiformPath();
        } else {
            enableFields();
        }
    }//GEN-LAST:event_customCuneiformCheckBoxActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        settings.setCustomPath(customCuneiformCheckBox.isSelected());
        settings.setPathToCuneiform(pathTextField.getText());
        settings.setRecognitionLanguage(recognitionLanguageComboBox.getSelectedIndex());
        settings.save();
        dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (settings != null) {
            if (settings.isCustomPath()) {
                enableFields();
                customCuneiformCheckBox.setSelected(true);
                pathTextField.setText(settings.getPathToCuneiform());
            } else {
                setDefaultCuneiformPath();
            }
            recognitionLanguageComboBox.setSelectedIndex(settings.getRecognitionLanguageId());
        }
    }//GEN-LAST:event_formWindowActivated


    
    private void fileChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserButtonActionPerformed
        JFileChooser selectExecDialog = new javax.swing.JFileChooser();
        int result = selectExecDialog.showOpenDialog(this);        
        
        if (result == JFileChooser.APPROVE_OPTION) {
            settings.setPathToCuneiform(selectExecDialog.getSelectedFile().toString());
        }
    }//GEN-LAST:event_fileChooserButtonActionPerformed

    private void disableFields() {
        pathTextField.setEnabled(false);
        fileChooserButton.setEnabled(false);
    }
    
    private void enableFields() {
        pathTextField.setEnabled(true);
        fileChooserButton.setEnabled(true);
    }
    
    private void setDefaultCuneiformPath() {
        pathTextField.setText(L10n.forString("settings.path.default"));
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox customCuneiformCheckBox;
    private javax.swing.JLabel defaultLanguageLabel;
    private javax.swing.JButton fileChooserButton;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JTextField pathTextField;
    private javax.swing.JComboBox recognitionLanguageComboBox;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
