/*
 * AboutBox.java
 *
 * Created on 08.04.2011, 2:30:16
 */

package ru.ifmo.juneiform.ui;

import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.URISyntaxException;
import org.apache.log4j.Logger;
import ru.ifmo.juneiform.L10n;

/**
 *
 * @author felix
 * @author Oleg "xplt" Kuznetsov
 */
public class AboutBox extends javax.swing.JDialog {

    private static final Logger log = Logger.getLogger(AboutBox.class);

    /** Creates new form AboutBox */
    public AboutBox() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        copyrightLabel = new javax.swing.JLabel();
        final String mainPageUrl = "https://bitbucket.org/Stepuk/juneiform";
        homepageLinkLabel = new javax.swing.JLabel();
        bugTextLabel = new javax.swing.JLabel();
        final String bugtrackerPageUrl = "https://bitbucket.org/Stepuk/juneiform/issues";
        bugLinkLabel = new javax.swing.JLabel();
        homepageTextLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        iconsTextLabel = new javax.swing.JLabel();
        final String iconsUrl = "http://www.fatcow.com/free-icons";
        iconsLinkLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About Juneiform");
        setIconImage(null);

        titleLabel.setFont(new java.awt.Font("Ubuntu", 1, 36));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleLabel.setText(" Juneiform 1.0");
        titleLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        titleLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        descriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descriptionLabel.setText(L10n.forString("about.description"));

        copyrightLabel.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        copyrightLabel.setText(L10n.forString("about.copyright"));

        homepageLinkLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homepageLinkLabel.setText("<html><font color=\"#0000ff\"><u>" + mainPageUrl + "</u></font></html>");
        homepageLinkLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
        homepageLinkLabel.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent event) {
                try {
                    java.awt.Desktop.getDesktop().browse(new java.net.URI(mainPageUrl));
                } catch (URISyntaxException ex) {
                    log.error("Unable to parse URL", ex);
                } catch (IOException ex) {
                    log.error("Unable to launch browser", ex);
                }
            }
        });

        bugTextLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        bugTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bugTextLabel.setText(L10n.forString("about.bug.tracker"));

        bugLinkLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bugLinkLabel.setText("<html><font color=\"#0000ff\"><u>" + bugtrackerPageUrl + "</u></font></html>");
        bugLinkLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
        bugLinkLabel.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent event) {
                try {
                    java.awt.Desktop.getDesktop().browse(new java.net.URI(bugtrackerPageUrl));
                } catch (URISyntaxException ex) {
                    log.error("Unable to parse URL", ex);
                } catch (IOException ex) {
                    log.error("Unable to launch browser", ex);
                }
            }
        });

        homepageTextLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        homepageTextLabel.setText(L10n.forString("about.homepage"));

        closeButton.setText(L10n.forString("about.ok.button"));
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        iconsTextLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        iconsTextLabel.setText(L10n.forString("about.icons.label"));

        iconsLinkLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconsLinkLabel.setText("<html><font color=\"#0000ff\"><u>" + L10n.forString("about.icons.authors") + "</u></font></html>");
        iconsLinkLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
        iconsLinkLabel.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent event) {
                try {
                    java.awt.Desktop.getDesktop().browse(new java.net.URI(iconsUrl));
                } catch (URISyntaxException ex) {
                    log.error("Unable to parse URL", ex);
                } catch (IOException ex) {
                    log.error("Unable to launch browser", ex);
                }
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(copyrightLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(titleLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(descriptionLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bugTextLabel)
                        .addGap(18, 18, 18)
                        .addComponent(bugLinkLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(homepageTextLabel)
                        .addGap(18, 18, 18)
                        .addComponent(homepageLinkLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(iconsTextLabel)
                        .addGap(18, 18, 18)
                        .addComponent(iconsLinkLabel)))
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(222, Short.MAX_VALUE)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descriptionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(copyrightLabel)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(homepageTextLabel)
                            .addComponent(homepageLinkLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bugTextLabel)
                            .addComponent(bugLinkLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(closeButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iconsTextLabel)
                            .addComponent(iconsLinkLabel))
                        .addGap(111, 111, 111))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bugLinkLabel;
    private javax.swing.JLabel bugTextLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel copyrightLabel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel homepageLinkLabel;
    private javax.swing.JLabel homepageTextLabel;
    private javax.swing.JLabel iconsLinkLabel;
    private javax.swing.JLabel iconsTextLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

}
